import type { TranslationKey } from "./i18n-dict"

export interface FolderTemplate {
  id: string
  name: string
  nameKey: TranslationKey
  icon: string
  description: string
  descKey: TranslationKey
  color?: string
  rootColor?: string
  rootIcon?: string
  subfolders: {
    name: string
    nameKey: TranslationKey
    icon?: string
    description?: string
    descKey?: TranslationKey
  }[]
}

export const FOLDER_TEMPLATES: FolderTemplate[] = [
  {
    id: "blank",
    name: "Blank",
    nameKey: "tpl.blank.name",
    icon: "📁",
    description: "An empty folder, no structure.",
    descKey: "tpl.blank.desc",
    rootIcon: "📁",
    subfolders: [],
  },
  {
    id: "project",
    name: "Project",
    nameKey: "tpl.project.name",
    icon: "📋",
    description: "Briefs, drafts, and final deliverables.",
    descKey: "tpl.project.desc",
    rootIcon: "📋",
    rootColor: "#0c4a6e",
    subfolders: [
      { name: "Briefs", nameKey: "tpl.project.briefs", icon: "📋", descKey: "tpl.project.briefsDesc" },
      { name: "Drafts", nameKey: "tpl.project.drafts", icon: "✏️", descKey: "tpl.project.draftsDesc" },
      { name: "Final", nameKey: "tpl.project.final", icon: "✨", descKey: "tpl.project.finalDesc" },
      { name: "References", nameKey: "tpl.project.references", icon: "🔖", descKey: "tpl.project.referencesDesc" },
    ],
  },
  {
    id: "client",
    name: "Client",
    nameKey: "tpl.client.name",
    icon: "🤝",
    description: "Discovery, deliverables, communications.",
    descKey: "tpl.client.desc",
    rootIcon: "🤝",
    rootColor: "#4c1d95",
    subfolders: [
      { name: "Discovery", nameKey: "tpl.client.discovery", icon: "🔍", descKey: "tpl.client.discoveryDesc" },
      { name: "Deliverables", nameKey: "tpl.client.deliverables", icon: "📦", descKey: "tpl.client.deliverablesDesc" },
      { name: "Comms", nameKey: "tpl.client.comms", icon: "📨", descKey: "tpl.client.commsDesc" },
      { name: "Invoices", nameKey: "tpl.client.invoices", icon: "🧾", descKey: "tpl.client.invoicesDesc" },
    ],
  },
  {
    id: "trip",
    name: "Trip",
    nameKey: "tpl.trip.name",
    icon: "✈️",
    description: "Plans, itineraries, photos.",
    descKey: "tpl.trip.desc",
    rootIcon: "✈️",
    rootColor: "#064e3b",
    subfolders: [
      { name: "Plans", nameKey: "tpl.trip.plans", icon: "🗺️", descKey: "tpl.trip.plansDesc" },
      { name: "Photos", nameKey: "tpl.trip.photos", icon: "📸", descKey: "tpl.trip.photosDesc" },
      { name: "Receipts", nameKey: "tpl.trip.receipts", icon: "🧾", descKey: "tpl.trip.receiptsDesc" },
    ],
  },
  {
    id: "brand",
    name: "Brand kit",
    nameKey: "tpl.brand.name",
    icon: "🎨",
    description: "Logos, palettes, type, guidelines.",
    descKey: "tpl.brand.desc",
    rootIcon: "🎨",
    rootColor: "#701a75",
    subfolders: [
      { name: "Logos", nameKey: "tpl.brand.logos", icon: "🏷️", descKey: "tpl.brand.logosDesc" },
      { name: "Palettes", nameKey: "tpl.brand.palettes", icon: "🎨", descKey: "tpl.brand.palettesDesc" },
      { name: "Type", nameKey: "tpl.brand.type", icon: "🔠", descKey: "tpl.brand.typeDesc" },
      { name: "Guidelines", nameKey: "tpl.brand.guidelines", icon: "📐", descKey: "tpl.brand.guidelinesDesc" },
    ],
  },
  {
    id: "shoot",
    name: "Photo shoot",
    nameKey: "tpl.shoot.name",
    icon: "📸",
    description: "Selects, raw, edited.",
    descKey: "tpl.shoot.desc",
    rootIcon: "📸",
    rootColor: "#7f1d1d",
    subfolders: [
      { name: "Raw", nameKey: "tpl.shoot.raw", icon: "📷", descKey: "tpl.shoot.rawDesc" },
      { name: "Selects", nameKey: "tpl.shoot.selects", icon: "👀", descKey: "tpl.shoot.selectsDesc" },
      { name: "Edited", nameKey: "tpl.shoot.edited", icon: "✨", descKey: "tpl.shoot.editedDesc" },
    ],
  },

  // ─── Insurance & inspection workflows ───────────────────────────────────
  {
    id: "insurance-incident",
    name: "Insurance incident report",
    nameKey: "tpl.insIncident.name",
    icon: "🚨",
    description: "Document an insurance incident with all supporting evidence.",
    descKey: "tpl.insIncident.desc",
    rootIcon: "🚨",
    rootColor: "#7f1d1d",
    subfolders: [
      { name: "Incident details", nameKey: "tpl.insIncident.details", icon: "📝", descKey: "tpl.insIncident.detailsDesc" },
      { name: "Photos & evidence", nameKey: "tpl.insIncident.photos", icon: "📸", descKey: "tpl.insIncident.photosDesc" },
      { name: "Witness statements", nameKey: "tpl.insIncident.witness", icon: "🗣️", descKey: "tpl.insIncident.witnessDesc" },
      { name: "Police report", nameKey: "tpl.insIncident.police", icon: "🚓", descKey: "tpl.insIncident.policeDesc" },
      { name: "Medical reports", nameKey: "tpl.insIncident.medical", icon: "🏥", descKey: "tpl.insIncident.medicalDesc" },
      { name: "Damage assessment", nameKey: "tpl.insIncident.damage", icon: "🔍", descKey: "tpl.insIncident.damageDesc" },
      { name: "Correspondence", nameKey: "tpl.insIncident.comms", icon: "📨", descKey: "tpl.insIncident.commsDesc" },
      { name: "Claim documents", nameKey: "tpl.insIncident.claim", icon: "📄", descKey: "tpl.insIncident.claimDesc" },
    ],
  },
  {
    id: "insurance-claim",
    name: "Insurance claim",
    nameKey: "tpl.insClaim.name",
    icon: "📑",
    description: "Track an insurance claim from filing through settlement.",
    descKey: "tpl.insClaim.desc",
    rootIcon: "📑",
    rootColor: "#1e3a8a",
    subfolders: [
      { name: "Claim forms", nameKey: "tpl.insClaim.forms", icon: "📋", descKey: "tpl.insClaim.formsDesc" },
      { name: "Supporting documents", nameKey: "tpl.insClaim.support", icon: "📎", descKey: "tpl.insClaim.supportDesc" },
      { name: "Correspondence", nameKey: "tpl.insClaim.comms", icon: "📨", descKey: "tpl.insClaim.commsDesc" },
      { name: "Approvals & denials", nameKey: "tpl.insClaim.decisions", icon: "✅", descKey: "tpl.insClaim.decisionsDesc" },
      { name: "Payments & settlements", nameKey: "tpl.insClaim.payments", icon: "💰", descKey: "tpl.insClaim.paymentsDesc" },
      { name: "Appeals", nameKey: "tpl.insClaim.appeals", icon: "🔁", descKey: "tpl.insClaim.appealsDesc" },
    ],
  },
  {
    id: "vehicle-inspection",
    name: "Vehicle inspection",
    nameKey: "tpl.vehicle.name",
    icon: "🚗",
    description: "Pre-claim or pre-policy vehicle inspection.",
    descKey: "tpl.vehicle.desc",
    rootIcon: "🚗",
    rootColor: "#3f3f46",
    subfolders: [
      { name: "Vehicle info & VIN", nameKey: "tpl.vehicle.info", icon: "🆔", descKey: "tpl.vehicle.infoDesc" },
      { name: "Exterior photos", nameKey: "tpl.vehicle.exterior", icon: "📷", descKey: "tpl.vehicle.exteriorDesc" },
      { name: "Interior photos", nameKey: "tpl.vehicle.interior", icon: "🪑", descKey: "tpl.vehicle.interiorDesc" },
      { name: "Damage areas", nameKey: "tpl.vehicle.damage", icon: "🔧", descKey: "tpl.vehicle.damageDesc" },
      { name: "Repair estimates", nameKey: "tpl.vehicle.estimates", icon: "🧾", descKey: "tpl.vehicle.estimatesDesc" },
      { name: "Registration & documents", nameKey: "tpl.vehicle.docs", icon: "📄", descKey: "tpl.vehicle.docsDesc" },
    ],
  },
  {
    id: "property-inspection",
    name: "Property inspection",
    nameKey: "tpl.property.name",
    icon: "🏠",
    description: "Home or commercial property inspection report.",
    descKey: "tpl.property.desc",
    rootIcon: "🏠",
    rootColor: "#854d0e",
    subfolders: [
      { name: "Property info", nameKey: "tpl.property.info", icon: "📍", descKey: "tpl.property.infoDesc" },
      { name: "Exterior", nameKey: "tpl.property.exterior", icon: "🏡", descKey: "tpl.property.exteriorDesc" },
      { name: "Interior — rooms", nameKey: "tpl.property.interior", icon: "🛋️", descKey: "tpl.property.interiorDesc" },
      { name: "Defects & issues", nameKey: "tpl.property.defects", icon: "⚠️", descKey: "tpl.property.defectsDesc" },
      { name: "Inventory", nameKey: "tpl.property.inventory", icon: "📦", descKey: "tpl.property.inventoryDesc" },
      { name: "Reports & certificates", nameKey: "tpl.property.reports", icon: "📜", descKey: "tpl.property.reportsDesc" },
    ],
  },
  {
    id: "workplace-incident",
    name: "Workplace incident",
    nameKey: "tpl.workIncident.name",
    icon: "⛑️",
    description: "Workplace safety incident with investigation and follow-up.",
    descKey: "tpl.workIncident.desc",
    rootIcon: "⛑️",
    rootColor: "#9a3412",
    subfolders: [
      { name: "Injury report", nameKey: "tpl.workIncident.report", icon: "📝", descKey: "tpl.workIncident.reportDesc" },
      { name: "Witness statements", nameKey: "tpl.workIncident.witness", icon: "🗣️", descKey: "tpl.workIncident.witnessDesc" },
      { name: "Site photos", nameKey: "tpl.workIncident.photos", icon: "📸", descKey: "tpl.workIncident.photosDesc" },
      { name: "Investigation", nameKey: "tpl.workIncident.investigation", icon: "🔍", descKey: "tpl.workIncident.investigationDesc" },
      { name: "Corrective actions", nameKey: "tpl.workIncident.corrective", icon: "✅", descKey: "tpl.workIncident.correctiveDesc" },
      { name: "Medical follow-up", nameKey: "tpl.workIncident.medical", icon: "🏥", descKey: "tpl.workIncident.medicalDesc" },
    ],
  },

  // ─── General business workflows ─────────────────────────────────────────
  {
    id: "legal-case",
    name: "Legal case",
    nameKey: "tpl.legal.name",
    icon: "⚖️",
    description: "Pleadings, evidence, and court filings.",
    descKey: "tpl.legal.desc",
    rootIcon: "⚖️",
    rootColor: "#1e1b4b",
    subfolders: [
      { name: "Pleadings", nameKey: "tpl.legal.pleadings", icon: "📜", descKey: "tpl.legal.pleadingsDesc" },
      { name: "Evidence", nameKey: "tpl.legal.evidence", icon: "🗂️", descKey: "tpl.legal.evidenceDesc" },
      { name: "Discovery", nameKey: "tpl.legal.discovery", icon: "🔎", descKey: "tpl.legal.discoveryDesc" },
      { name: "Court filings", nameKey: "tpl.legal.filings", icon: "🏛️", descKey: "tpl.legal.filingsDesc" },
      { name: "Correspondence", nameKey: "tpl.legal.comms", icon: "📨", descKey: "tpl.legal.commsDesc" },
      { name: "Notes & strategy", nameKey: "tpl.legal.notes", icon: "📝", descKey: "tpl.legal.notesDesc" },
    ],
  },
  {
    id: "employee-file",
    name: "Employee file",
    nameKey: "tpl.employee.name",
    icon: "👤",
    description: "Application, contracts, reviews, and training.",
    descKey: "tpl.employee.desc",
    rootIcon: "👤",
    rootColor: "#0f766e",
    subfolders: [
      { name: "Application & resume", nameKey: "tpl.employee.application", icon: "📄", descKey: "tpl.employee.applicationDesc" },
      { name: "Contracts", nameKey: "tpl.employee.contracts", icon: "✍️", descKey: "tpl.employee.contractsDesc" },
      { name: "Performance reviews", nameKey: "tpl.employee.reviews", icon: "⭐", descKey: "tpl.employee.reviewsDesc" },
      { name: "Training", nameKey: "tpl.employee.training", icon: "🎓", descKey: "tpl.employee.trainingDesc" },
      { name: "Payroll", nameKey: "tpl.employee.payroll", icon: "💵", descKey: "tpl.employee.payrollDesc" },
      { name: "Notes", nameKey: "tpl.employee.notes", icon: "📝", descKey: "tpl.employee.notesDesc" },
    ],
  },
  {
    id: "real-estate",
    name: "Property listing",
    nameKey: "tpl.realEstate.name",
    icon: "🏘️",
    description: "Listing photos, floor plans, and marketing assets.",
    descKey: "tpl.realEstate.desc",
    rootIcon: "🏘️",
    rootColor: "#3f6212",
    subfolders: [
      { name: "Photos", nameKey: "tpl.realEstate.photos", icon: "📸", descKey: "tpl.realEstate.photosDesc" },
      { name: "Floor plans", nameKey: "tpl.realEstate.plans", icon: "📐", descKey: "tpl.realEstate.plansDesc" },
      { name: "Documents", nameKey: "tpl.realEstate.docs", icon: "📄", descKey: "tpl.realEstate.docsDesc" },
      { name: "Marketing", nameKey: "tpl.realEstate.marketing", icon: "📣", descKey: "tpl.realEstate.marketingDesc" },
      { name: "Inspections", nameKey: "tpl.realEstate.inspections", icon: "🔍", descKey: "tpl.realEstate.inspectionsDesc" },
      { name: "Offers", nameKey: "tpl.realEstate.offers", icon: "💼", descKey: "tpl.realEstate.offersDesc" },
    ],
  },
  {
    id: "construction",
    name: "Construction project",
    nameKey: "tpl.construction.name",
    icon: "🏗️",
    description: "Plans, permits, photos, and invoices.",
    descKey: "tpl.construction.desc",
    rootIcon: "🏗️",
    rootColor: "#78350f",
    subfolders: [
      { name: "Plans & drawings", nameKey: "tpl.construction.plans", icon: "📐", descKey: "tpl.construction.plansDesc" },
      { name: "Permits", nameKey: "tpl.construction.permits", icon: "📋", descKey: "tpl.construction.permitsDesc" },
      { name: "Site photos", nameKey: "tpl.construction.photos", icon: "📸", descKey: "tpl.construction.photosDesc" },
      { name: "Invoices & receipts", nameKey: "tpl.construction.invoices", icon: "🧾", descKey: "tpl.construction.invoicesDesc" },
      { name: "Subcontractors", nameKey: "tpl.construction.subs", icon: "🛠️", descKey: "tpl.construction.subsDesc" },
      { name: "Punch list", nameKey: "tpl.construction.punch", icon: "✓", descKey: "tpl.construction.punchDesc" },
    ],
  },
  {
    id: "event",
    name: "Event",
    nameKey: "tpl.event.name",
    icon: "🎉",
    description: "Wedding, conference, party — plan it end to end.",
    descKey: "tpl.event.desc",
    rootIcon: "🎉",
    rootColor: "#86198f",
    subfolders: [
      { name: "Concept & brief", nameKey: "tpl.event.concept", icon: "💡", descKey: "tpl.event.conceptDesc" },
      { name: "Venue", nameKey: "tpl.event.venue", icon: "📍", descKey: "tpl.event.venueDesc" },
      { name: "Vendors", nameKey: "tpl.event.vendors", icon: "🤝", descKey: "tpl.event.vendorsDesc" },
      { name: "Attendees", nameKey: "tpl.event.attendees", icon: "👥", descKey: "tpl.event.attendeesDesc" },
      { name: "Budget", nameKey: "tpl.event.budget", icon: "💰", descKey: "tpl.event.budgetDesc" },
      { name: "Day-of photos", nameKey: "tpl.event.photos", icon: "📸", descKey: "tpl.event.photosDesc" },
    ],
  },
]
